/**
 * Builds apps/web for the iPhone WebView and writes it as one inline HTML string module:
 * apps/ios/src/webApp.generated.ts. Run after changing anything under apps/web or packages/engine.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../../..');
const webDir = path.join(root, 'apps/web');
const outDir = path.join(webDir, 'dist-device');
const target = path.join(root, 'apps/ios/src/webApp.generated.ts');

execFileSync(
  process.execPath,
  [path.join(root, 'node_modules/vite/bin/vite.js'), 'build', '--config', 'vite.device.config.ts', '--logLevel', 'warn'],
  { cwd: webDir, stdio: 'inherit' },
);

const assetsDir = path.join(outDir, 'assets');
const files = readdirSync(assetsDir);
const jsFile = files.find((f) => f.endsWith('.js'));
const cssFile = files.find((f) => f.endsWith('.css'));
if (!jsFile) throw new Error('device build produced no JS bundle');

const iconDataUri = `data:image/png;base64,${readFileSync(path.join(webDir, 'public/icon-192.png')).toString('base64')}`;
let js = readFileSync(path.join(assetsDir, jsFile), 'utf8')
  .replaceAll('"/icon-192.png"', JSON.stringify(iconDataUri))
  .replace(/<\/script/gi, '<\\/script');
const css = cssFile ? readFileSync(path.join(assetsDir, cssFile), 'utf8').replace(/<\/style/gi, '<\\/style') : '';

let html = readFileSync(path.join(outDir, 'index.html'), 'utf8');
html = html
  .replace(/<link rel="(icon|apple-touch-icon|manifest)"[^>]*>\s*/g, '')
  .replace(/<script type="module" crossorigin src="[^"]+"><\/script>/, '')
  .replace(/<link rel="stylesheet" crossorigin href="[^"]+">/, '')
  // Function replacers: the bundle contains `$&` / `` $` `` sequences a string replacement would expand.
  .replace('</head>', () => `<style>${css}</style>\n</head>`)
  .replace('</body>', () => `<script type="module">${js}</script>\n</body>`);

if (html.includes('src="./assets/') || html.includes('href="./assets/')) {
  throw new Error('device HTML still references external assets');
}

writeFileSync(
  target,
  `// Generated by apps/ios/scripts/build-web-app.mjs from apps/web. Do not edit by hand.\n` +
    `export const WEB_APP_HTML = ${JSON.stringify(html)};\n`,
);
console.log(`wrote ${path.relative(root, target)} (${Math.round(html.length / 1024)} KB)`);
